### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by IanDuncanT** [YetAnotherPackageInstaller/rewrite#9]
Create translations for commands. I don't know any languages that would help, so please write translations for any languages you know.

**Comment by Wabri** [comment]
I can do that, but where and how do you want it?

**Comment by IanDuncanT** [comment]
For example the text in the gui part of the rewrite is in english, but I just need translations for other languages such as Italian. I will write the code to update it, but just write a .ini file with a section of [GUI] and values for each gui element.
